export enum SecureStorageKeys {
  AuthSession = "auth.session",
  AccessToken = "auth.access_token",
  RefreshToken = "auth.refresh_token",
  SessionMeta = "auth.session_meta",
}

export enum KvStorageKeys {
  AppLanguage = "app.language",
  ThemeMode = "app.theme_mode",
  WalletChainId = "wallet.chain_id",
  WalletRpcIndex = "wallet.rpc_index",
  PasskeyHistory = "auth.passkey_history",
  UserProfile = "auth.user_profile",
  UserAvatarCache = "auth.user_avatar_cache",
  NetworkLogoCache = "app.network_logo_cache",
  VerificationCodeCountdownEndAt = "auth.verification_code_countdown_end_at",
  EmailBindCountdownEndAt = "auth.email_bind_countdown_end_at",
  EmailUnbindCountdownEndAt = "auth.email_unbind_countdown_end_at",
  ShowBalance = "home.show_balance",
  HomeBalanceCache = "home.balance_cache",
  SelectedCurrency = "home.selected_currency",
  SelectedInviteLevel = "home.selected_invite_level",
  OrdersTxlogsCache = "orders.txlogs_cache",
  OrdersBillCache = "orders.bill_cache",
  OrdersDetailCache = "orders.detail_cache",
  TransferDraft = "transfer.draft",
  SelectTokenPageReload = "transfer.select_token_page_reload",
  HomePageNeedRefresh = "home.home_page_need_refresh",
  WechatInterceptorShown = "support.wechat_interceptor_shown",
  OriginalTargetPath = "support.original_target_path",
  ReceiveGuideDismissed = "receive.guide.dismissed",
  ReceiveShowedList = "receive.showed_list",
  ReceiveChainColorCache = "receive.chain_color_cache",
  CopouchSortByAmount = "copouch.sort_by_amount",
  CopouchGuideDismissedWalletIds = "copouch.guide.dismissed_wallet_ids",
}
