# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source ENV.fetch('COCOAPODS_SOURCE', 'https://cdn.cocoapods.org/')

platform :ios, min_ios_version_supported
prepare_react_native_project!
inhibit_all_warnings!

def strip_duplicate_cpp_stdlib_linker_flag(installer)
  # Aggregate Pods xcconfig files already inherit libc++ from Xcode settings.
  Dir.glob(File.join(installer.sandbox.target_support_files_root, 'Pods-*', '*.xcconfig')).each do |xcconfig_path|
    contents = File.read(xcconfig_path)
    next unless contents.include?('-l"c++"')

    updated = contents.gsub(/\s-l"c\+\+"/, '')
    next if updated == contents

    File.write(xcconfig_path, updated)
  end
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'CPCashRN' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'CPCashRNTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    strip_duplicate_cpp_stdlib_linker_flag(installer)

    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        next unless phase.name == "[CP-User] [RN]Check rncore"

        phase.always_out_of_date = "1"
      end
    end
  end
end
